# Generated by Django 3.0.5 on 2023-05-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_yashu_disease_yashu_name_yashu_patient_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yashu',
            name='course_duration',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='yashu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='yashu',
            name='age',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='yashu',
            name='id',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        
    ]
