# Generated by Django 3.0.5 on 2023-06-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('disease_effect', models.TextField()),
                ('symptoms', models.TextField()),
                ('precautions', models.TextField()),
                ('course_duration', models.TextField()),
            ],
        ),
    ]
